- name: postgres playbook
  hosts: southwest
  sudo: yes
  remote_user: vagrant

  tasks:
  - name: ensure apt cache is up to date
    action: apt update_cache=yes
  - name: ensure packages are installed
    action: apt name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

- hosts: southwest
  sudo: yes
  sudo_user: postgres

  vars:
    dbname: myapp
    dbuser: dbadmin
    dbpassword: password

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
